import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 30,
    paddingTop: 50,
    backgroundColor: '#F9F4E2',
  },
  constainerKeyBoard: {
    flex: 1,
  },
  containerText: {
    display: 'flex',
    flex: 1,
    marginStart: 30,
    height: 30,
    color: '#fff',
    alignItems: 'center',
    fontWeight: 'bold',
    fontFamily: 'SemiBold',
    fontSize: 25,
    textShadowRadius: 3,
    elevation: 10,
  },
  animatedContainer: {
    width: '100%',
    alignItems: 'center',
  },
  containerTextActivity: {
    display: 'flex',
    flex: 1,
    marginStart: 2,
    color: '#fff',
    alignItems: 'center',
    fontWeight: 'bold',
    fontFamily: 'SemiBold',
    fontSize: 25,
    textShadowRadius: 3,
    elevation: 10,
  },
  activityButtonContainer: {
    paddingVertical: 3,
    paddingHorizontal: 30,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 10,
  },
  inner: {
    flex: 1,
    justifyContent: 'space-between',
  },
  content: {
    alignItems: 'center',
  },
  title: {
    fontSize: 50,
    textAlign: 'center',
    marginBottom: 10,
  },
  image: {
    width: 170,
    height: 170,
    marginBottom: 20,
  },
  iconsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 20,
  },
  emotionButtonContainer: {
    width: '100%',
    alignItems: 'center',
    paddingVertical: 13,
    borderWidth: 0,
    borderColor: '#ddd',
    borderRadius: 15,
    marginBottom: 20,
    backgroundColor: '#FFD700',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 10,
  },
  buttonRow: {
    flexDirection: 'row',
    marginBottom: 7,
  },
  button: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 13,
    paddingVertical: 6,
    marginHorizontal: 5,
    marginBottom: 10,
    borderRadius: 15,
  },
  buttonText: {
    color: '#000',
  },
  scrollContainer: {
    display: 'flex',
    width: '100%',
    alignItems: 'center',
  },
  textInput: {
    backgroundColor: '#FFF',
    padding: 10,
    borderRadius: 15,
    paddingHorizontal: 50,
    marginTop: 10,
    height: 100,
    verticalAlign: 'top',
  },
  buttonAdd: {
    width: 10,
    padding: 10,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
  },
  plusContainer: {
    display: 'flex',
    marginEnd: 20,
    marginBottom: 15,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  plusContainerActivity: {
    display: 'flex',
    left: 12,
    marginTop: 10,
    marginBottom: 15,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  plusText: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'yellow',
    height: 48,
    marginBottom: 10,
    fontSize: 40,
    fontWeight: 'bold',
  },
  selectedButton: {
    backgroundColor: '#cccccc',
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    margin: 1,
  },
  saveButton: {
    backgroundColor: '#FFD700',
    padding: 10,
    borderRadius: 15,
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 10,
  },
  saveButtonText: {
    color: '#FFFF',
    fontWeight: 'bold',
    fontSize: 20,
  },
  addEmotionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    paddingHorizontal: 10,
  },
  input: {
    flex: 1,
    backgroundColor: '#FFF',
    borderRadius: 15,
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginRight: 10,
    elevation: 4,
    borderColor: '#ddd',
    borderWidth: 1,
  },
  addButton: {
    borderRadius: 15,
    paddingVertical: 10,
    paddingHorizontal: 15,
    elevation: 4,
    borderColor: '#ddd',
    borderWidth: 1,
  },
  addButtonText: {
    color: '#FFF',
    fontWeight: 'bold',
  },
  page: {
    width: SCREEN_WIDTH - 40,
    paddingHorizontal: 10,
  },
  descriptionContainer: {
    width: '100%',
    height: 200,
    marginTop: 20,
    alignItems: 'center',
    paddingHorizontal:50,
    paddingVertical : 30,
    borderRadius: 10,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

  },
  descriptionInput: {
    backgroundColor: '#FFF',
    borderRadius: 10,
    padding: 30,
    width: 210 ,
    height: 140,
    textAlignVertical: 'top', 
  },
});
